### ISSUE TITLE
using webrat (and other) methods from Gizmo::Page for better encapsulation

### ISSUE THREAD

**Issue by ghost** [icaruswings/gizmo#1]
I was just trying out gizmo on a project, and had an idea. What if, during your `on_page_with` block, you had helper methods that abstracted actions on the page?

Imagine doing this:

```
on_page_with :login do |page|
  page.login 'admin@admin.com', 'test'
end
```

This is a pretty simple case, but I think it has a lot of potential to reduce the unDRYness of integration tests that happens so often.

It's actually not far of implementation-wise. `Gizmo::Page` instances already have a copy of driver/spec/etc they are running from, and store that as `@browser`. Using this, I was able to implement that page as:

```
module PageWithLogin

  def valid?
    has_selector?('#session_email') && has_selector?('#session_password')
  end

  def login(email, password)
    @browser.fill_in 'Email', :with => email
    @browser.fill_in 'Password', :with => password
    @browser.click_button 'Login'
  end

end
```

It's probably not a great idea to be using an instance variable here, so an attr reader would be more appropriate. Or... even crazier, maybe method_missing could try passing stuff to `browser`, or less crazy, could delegate known methods to it.

Thoughts?

**Comment by icaruswings** [comment]
thanks for your input.. we really appreciate the feedback, and we are pretty happy that at least one other person so far has had a go at Gizmo.

funnily enough,  this is a problem we have faced alot while using our page model implementation in anger here at REA.

we have so far tried to discourage the use of actions inside page mixins in favour of just leaving them in the steps after finding them to be a bit confusing and increasingly hard to debug in a large test suite.

but that was mostly due to the strange api - namely the use of @browser everywhere and the fact that actions end up just looking like all the other 'selector' methods in the page mixins.

its obvious though that there needs to be an elegant way of defining actions in the mixins and you're definitely right, it will go a long way to further DRYing up the assertions.

we have come up with something we like, along the lines of:

```
module PageWithLogin

  def valid?
    has_selector?('#session_email') && has_selector?('#session_password')
  end

  define_action :login do | email, password |
    fill_in 'Email', :with => email
    fill_in 'Password', :with => password
    click_button 'Login'
  end

end
```

internally (thanks to your comments) we delegate the page interactions via method_missing to the @browser session object

its almost ready to push to github, probably on another branch, so we can sanity test it a little here before pushing to rubygems.

what do you think?

**Comment by icaruswings** [comment]
oh, you probably want to know how to call it from your steps.

```
on_page_with :login do |page|
  page.perform :login, 'admin@admin.com', 'test'
end
```

**Comment by technicalpickles** [comment]
That was me earlier, but was accidentally earlier posting from a shared account.

I find it a little funny that you say you left actions in your steps because of maintainability/debugging, but I'm imagining moving that kind of stuff into gizmo classes for improving those very things :) Granted, my gizmo suite is still pretty small, so I don't know how it'd scale.

I'm not sure I'm convinced of the use of `define_action` and `perform`. If it's a matter of telling selectors from actions, maybe just have a convention of naming action methods like `perform_login`? To me, having `define_action` and `perform` add an extra step that's not really needed when it can just be a method. Plus, it'd be a real method, so you could use ctags to navigate to the definition easily :)

**Comment by impurist** [comment]
Thanks for the further input.

You make some good points, though our recent changes will not effect the "methods with conventions" usage you suggest. While I agree with you in principle we have however found that DSLs help us better manage conventions over several projects. Our test suites are numerous and range from 50 -  3500 scenarios. There have been a number of poor examples of action methods in page mixins that caused all kinds of headaches. Enforcing good habits via DSLs helps us write more maintainable tests across teams and projects.

The define_action functionality is an opt-in feature and requires you to include the Gizmo::PageMixin module so your free choose your own convention.

In response to your original comment we now delegate all the session/browser methods to method missing to the method browser(which returns @browser). So your initial use case should be satisfied and thanks for the suggestions.

**Comment by technicalpickles** [comment]
Sounds great to me. Will check out the new release, thanks!

**Comment by icaruswings** [comment]
no problems at all. Im going to close this issue, with the @browser stuff sorted out. and we'll get some docs written for the define action stuff to make it a little clearer.

please let us know if you have any other feedback :)
